### ISSUE TITLE
pdf link of paper?

### ISSUE THREAD

**Issue by ShuhaoGithub** [ddd9898/DeepNano#1]
Thank you for this open-sourced tool! Is there a link to pdf of this paper somewhere?

**Comment by ddd9898** [comment]
Thank you for your interest! Unfortunately, the PDF cannot be shared publicly due to copyright restrictions. However, here is a shareable link provided by the publisher: https://rdcu.be/d2Bwt. Besides, you can also access the paper through the publisher's website https://doi.org/10.1038/s42256-024-00940-5 or through institutional access if you have it. Feel free to download the paper from there.

**Comment by ShuhaoGithub** [comment]
https://rdcu.be/d2Bwt works perfect! Thanks!
